-- MySQL Script generated by MySQL Workbench
-- Thu Mar 15 23:59:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eHealth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eHealth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eHealth` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ehealth
-- -----------------------------------------------------
USE `eHealth` ;

-- -----------------------------------------------------
-- Table `eHealth`.`input2process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `input2process`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `input2process` (
  `V1` int(11) NOT NULL,
  `V2` int(11) DEFAULT NULL,
  `V3` int(11) DEFAULT NULL,
  `V4` decimal(4,2) DEFAULT NULL,
  `V5` int(11) DEFAULT NULL,
  `V6` varchar(20) DEFAULT NULL,
  `V7` varchar(20) DEFAULT NULL,
  `V8` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`V1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;



-- -----------------------------------------------------
-- Table `eHealth`.`results2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `results2` (
  `V1` INT NOT NULL,
  `V2` INT NULL,
  `V3` INT NULL,
  `V4` INT NULL,
  `V5` INT NULL,
  `V6` varchar(20) NULL,
  `V7` varchar(20) NULL,
  `V8` varchar(30) NULL,
  PRIMARY KEY (`V1`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


